### PR TITLE
Godot 4 stable

### PR DESCRIPTION
**Pull request by RancidMilkGames**
# Updated to Godot 4 stable

* Fixed api changes between last release and Godot 4 stable
* Also added a free cam for previewing the sample scene, could understand if that's not wanted

### CODE REVIEW

**Comment by Arnklit** [comment]
Hi @RancidMilkGames, thanks so much. I've already been working on some of these things, I just haven't pushed my local changes. I'll see about getting my updates pushed and seeing if there is anything I missed that you caught.

**Comment by CentiGames** [comment]
Hi, any updates on this? It would be great if we had this awesome plugin for Godot 4 as well :)

**Comment by Arnklit** [comment]
@CentiGames not much happening at the moment. It's basically on hold until a decent terrain add-on is available for 4.0 as I find it pretty pointless to work on and use without that.

**Comment by CentiGames** [comment]
The [Godot 4 branch of Zylann's Heightmap Terran Plugin](https://github.com/Zylann/godot_heightmap_plugin/tree/godot4) has already been updated to Godot 4.1 and works pretty well, even if it's not (yet) available on the Asset Library. I even mentioned some bugs, and they have been fixed pretty quickly. 
Otherwise, there's also [this Godot 4.1 3D Terrain Plugin](https://godotengine.org/asset-library/asset/1920), but I haven't tested that one yet.

**Comment by Arnklit** [comment]
Yeah I believe there is another couple of terrain systems that are close to being released. I have not had time to try them out.
So yeah hopefully I will move on this soon, at least get it back to working as well as it did in 3.x, which is a pretty small amount of work. 

I do want to rewrite it from scratch and make it able to do much more than it currently does, but I am very pressed for time at the moment. I'm back to working full time and am under freelance contract for other deliverables over the summer, so probably not much will happen until the fall. I might find the time to get it back to working, but no new features.

**Comment by tuto193** [comment]
Hey @Arnklit ! I've seen your comments underneath the videos of [Tokisan Games](https://github.com/TokisanGames/Terrain3D) and I do understand that you're busy, but still wanted to know,how it was coming along. Would otherwise love to contribute to help expedite the process :smile:

**Comment by mkay-dev** [comment]
Just here to say I am also really hoping for an update. @RancidMilkGames update sadly isn't complete, the UI elements being entirely missing for me among other things. 

> Yeah I believe there is another couple of terrain systems that are close to being released. I have not had time to try them out. So yeah hopefully I will move on this soon, at least get it back to working as well as it did in 3.x, which is a pretty small amount of work.

There are two rapidly advancing terrain systems I can recommend. Both already fairly far along to being production ready. 
https://github.com/TokisanGames/Terrain3D
https://github.com/mohsenph69/Godot-MTerrain-plugin

**Comment by Arnklit** [comment]
Hi Guys, not gonna make any promises right now as I keep being pulled in other directions that postpones my work on this.

If anyone wants to cleanup the Godot 4 ports feel free and they can ping me on Discord with any questions.

**Comment by TokisanGames** [comment]
@Arnklit Isn't this a PR that already converted Waterways to GD4? And you [mentioned ](https://github.com/Arnklit/Waterways/pull/23#issuecomment-1510209644) in April that you already had some changes locally that just need to be pushed.

**Comment by Arnklit** [comment]
This is not relevant as 4_0 branch is ahead of this.

**Pull request closed without merging**
